
spring:
  application:
    name: consul-provider-cloud
  cloud:
    consul:
      host: 127.0.0.1
      port: 8900
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
server:
  port: 18089
